version: '3.8'

services:
  app:
    image: cvivadim/todo-nextjs:latest
    restart: always
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs
    depends_on:
      - app

volumes:
  mongo_data:
  certs:
