version: '3.9'

services:
  # ======================
  # Next.js приложение
  # ======================
  app:
    image: cvivadim/todo-nextjs:latest
    restart: always
    environment:
      - MONGODB_URI=${MONGODB_URI}
    expose:
      - '3000'
    depends_on:
      - mongo

  # ======================
  # MongoDB
  # ======================
  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo_data:/data/db

  # ======================
  # Nginx для HTTPS
  # ======================
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs
    depends_on:
      - app

  # ======================
  # Certbot для Cloudflare DNS
  # ======================
  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
    entrypoint: ''
    command: >
      sh -c "trap exit TERM;
             while :; do
               certbot renew --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini --post-hook 'docker kill -s HUP nginx';
               sleep 12h;
             done"

volumes:
  mongo_data:
  certs:
