version: '3.8'

services:
  # ======================
  # Next.js приложение
  # ======================
  app:
    build:
      context: ...
      dockerfile: Dockerfile
      args:
        MONGODB_URI: mongodb://mongo:27017/todo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/todo
    expose:
      - '3000'

  # ======================
  # MongoDB
  # ======================
  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo_data:/data/db

  # ======================
  # Nginx для поддоменов
  # ======================
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs
    depends_on:
      - app

volumes:
  mongo_data:
  certs:
