version: '3.8'

services:
  app:
    image: cvivadim/todo-nextjs:latest
    restart: always
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/todo
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
      interval: 5s
      retries: 5

volumes:
  mongo_data:
