version: '3.9'

services:
  app:
    build: .
    container_name: todo-nextjs_app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - '3000:3000'

  nginx:
    image: nginx:alpine
    container_name: todo-nextjs_nginx
    ports:
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs:ro
    depends_on:
      - app
