version: '3.8'

services:
  app:
    image: cvivadim/todo-nextjs:latest
    restart: always
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=${MONGODB_URI}

  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
