version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: todo-nextjs-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: todo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: todo-nextjs-app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://root:password@mongo:27017/todo?authSource=admin
    depends_on:
      - mongo
    ports:
      - '3000:3000'

  nginx:
    image: nginx:alpine
    container_name: todo-nextjs-nginx
    depends_on:
      - app
    ports:
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs:ro

volumes:
  mongo_data:
