version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: todo-nextjs_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: todo
  healthcheck:
    test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
    interval: 5s
    timeout: 5s
    retries: 5

  app:
    build: .
    container_name: todo-nextjs_app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://root:password@mongo:27017/todo?authSource=admin
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  nginx:
    image: nginx:alpine
    container_name: todo-nextjs_nginx
    ports:
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs:ro
    depends_on:
      - app
