version:
  '3.8'

  # ======================
  # Next.js приложение
  # ======================
services:
  app:
    image: cvivadim/todo-nextjs:latest
    restart: always
    environment:
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongo

  # ======================
  # MongoDB
  # ======================
  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo_data:/data/db

  # ======================
  # Nginx для поддоменов
  # ======================
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs
    depends_on:
      - app

volumes:
  mongo_data:
  certs:
